variables:
  PROJECT_PATH: arsnova.click

build-and-deploy:
  stage: deploy
  only:
    - staging
  script:
    - test -d package-metadata && rm -rf /opt/meteor/package-metadata && mv package-metadata /opt/meteor/
    - cd "$CI_PROJECT_DIR/$PROJECT_PATH"
    - meteor --verbose build --directory --server "$STAGING_HTTP_URL" build
    - chmod -R a+rX,ug+w build
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh && echo "$STAGING_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - scp -r build/bundle/* "$STAGING_SSH_URL"
    - mv /opt/meteor/package-metadata "$CI_PROJECT_DIR/"
  cache:
    paths:
      - package-metadata
      - $PROJECT_PATH/.meteor/local
